name: dnd_app
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  get_it: ^7.6.0
  go_router: ^13.0.0
  fpdart: ^1.1.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
